name: alpha_num_recognizer_android
description: "Phonetic Speech Recognition Flutter Plugin for Android"
version: 0.0.1
homepage:
# Author: Prayag Dhakal   <prayagdhakal123@gmail.com>
environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.prayag.alpha_num_recognizer_android
        pluginClass: SentenceRecognizerAndroidPlugin